### ISSUE TITLE
Duty Officer 'Automated General Notice' List

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Web-Interface#24]
Needs to be ported from /r/donoticelist.php into the web interface.

To-Do list:
- [x] Update table structure/Relocate table to the main database (Include field to link a notice to a forum post for the DO announcements thread)
- [ ] System to randomly select and display a notice, and display all notices (Probably on the same page like it's currently setup)
- [x] Routes entry for URLs
- [x] Menu entry
- [x] 'Show/Edit' handler
- [x] 'Delete' handler
- [x] 'Add' handler

Possible idea:
- [ ] Speak with Skull to implement a system in-game to automatically select a notice from this lsit and send it at the 0:30, 1:30, 2:30, etc marks in game.

**Comment by SierraKomodo** [comment]
Index listing and DB structure are done.

**Comment by Arrow768** [comment]
Only the serverside stuff is missing (automatically selecting and displaying one ingame)

**Comment by Arrow768** [comment]
Done once the serverside pull is merged
