### ISSUE TITLE
Duty Officer 'CCIA Action' list

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Web-Interface#25]
Interface to allow DOs to enter suspensions, injunctions, and other IC actions taken against characters, and to allow players to see active actions against their characters and head of staff whitelistees to see all active actions.

To replace the thread that's a pain to manage.

To Do:
 - [x] Create DB table structure.
 - [x] Interface to enter/delete/manage entries for DOs
 -- Include 'automatic expiration' of temporary suspensions/injunctions that are given a timeline
 - [x] Interface to view entries for DOs/Players/Heads

**Comment by Arrow768** [comment]
The tablestructure already exists here:
https://github.com/Aurorastation/Web-Interface/blob/master/database/migrations/2016_03_04_230051_create_cciaactionlist.php

**Comment by Arrow768** [comment]
Change the CCIA Action the following way:
* Link it to a char instead of a player.
* Add a new do notes field to the char records.

**Comment by Arrow768** [comment]
Done DO Actions / Records have been implemented in 0.5.0
