### ISSUE TITLE
'>' symbols added to additional lines when sending a command report

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Web-Interface#53]
https://byond.aurorastation.org/server/live/coms

`Central Command Update`

`TEST`

`This is a test message ((Testing the updated WI command report function))`
`>`
`>- CCIAAMS, Central Command Internal Affairs Agent, NTCC Odin`

**Comment by Arrow768** [comment]
This has been fixed with a Update of the Serverside API.
Also multiline messages are now displayed properly.
