### ISSUE TITLE
Faxxes sent through the web interface appear to have a character limit

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Web-Interface#57]
I didn't catch what the exact character limit was as the round was ending at the time and I had to send in a report using the manual method instead. A lengthy fax containing the below message was cut off after the 'Additionally, according to' portion, and the SIGN field was appended.

> First and foremost, we want to ensure the chief medical officer and research director are aware of the following: You are employed by us to work on board a research station to conduct research. We expect you to be able to collaborate and cooperate peaceably on matters such as this, not bicker at eachother and cause incidents. The chief medical officer is fully qualified to conduct exploratory surgeries. The research director is fully qualified to handle scientific reports. Please combine your skills in the future to provide results instead of complaints.

>Upon review of the statements provided by the CMO, responding security officer, and the research director, we have determined that the chief medical officer was acting within the bounds of their official capacity. According to signed testimony of the officer, the research department was already in possession of additional samples of these 'bluespace bear' specimens. Multiple medical staff attested to the research drector's tresspass, as noted in the officer's report. In this particular instance, the stated charge of trespassing for the research director does appear to be valid, and the complaint of exceeding official powers appears to be invalid.

>Additionally, according to the CMO's report, the research director has now been exceeding official powers, including possible tampering with cyborg control consoles. We request a thorough investigation into the matter be conducted by security personnel and a report forwarded back to CCIA for additional review.

**Comment by Arrow768** [comment]
The query is sent and received properly by the server.
This also applies to announcements

**Comment by Arrow768** [comment]
This happens during sanitation of the messages on the server.
There is a character limit of 1024 chars.
