### ISSUE TITLE
Make DO Actions visible on character information screens

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Web-Interface#67]
This is a request to have a table of the relevant DO Actions listed at this url ( https://byond.aurorastation.org/ccia/actionlist ) be displayed somewhere on the character information page (Example: https://byond.aurorastation.org/server/chars/1478/show ), like security incidents are.

**Comment by Arrow768** [comment]
Current CCIA Actions for all chars are now shown on the user dashboard displayed when logging in.
And a warning message is displayed on top if a char is linked to one or more active ccia actions
